### ISSUE TITLE
Add functionality for LSA

### ISSUE THREAD

**Issue by TommyJones** [TommyJones/textmineR#10]
SVD for sparse matrices from irlba

**Comment by dselivanov** [comment]
Worth to check [RSpectra](https://github.com/yixuan/RSpectra) package. Here are [benchmarks](http://statr.me/2016/02/large-scale-eigen-and-svd-with-rarpack/) for [rARPACK](https://github.com/yixuan/rARPACK), which is a wrapper of RSpectra.

**Comment by TommyJones** [comment]
Thanks. I'll check it out and benchmark it with irlba, as well as compare results numerically. I'll open a new issue for this.
