### ISSUE TITLE
Compare RSpectra to current implementation of SVD

### ISSUE THREAD

**Issue by TommyJones** [TommyJones/textmineR#13]
From @dselivanov "Worth to check [RSpectra](https://github.com/yixuan/RSpectra) package. Here are [benchmarks](http://statr.me/2016/02/large-scale-eigen-and-svd-with-rarpack/) for [rARPACK](https://github.com/yixuan/rARPACK), which is a wrapper of RSpectra."

**Comment by dselivanov** [comment]
Another nice package I just discovered - [softImpute](https://cran.r-project.org/web/packages/softImpute/) by Trevor Hastie and Rahul Mazumder. It has very fast `svd.als()` function for low rank soft-thresholded svd by alternating orthogonal ridge regression.

**Comment by TommyJones** [comment]
Just confirmed RSpectra is *much* faster than irlba. Closing this issue and opening a new one for me to make the change.

**Comment by yixuan** [comment]
Just came across this discussion when I was looking back on an issue of `RSpectra`. Thank you both for the positive comments on `RSpectra`. :wink:
