### ISSUE TITLE
Parallel execution fails on Windows when TmParallelApply called from inside a function

### ISSUE THREAD

**Issue by tlutz1** [TommyJones/textmineR#21]
I think it has something to do with the environment that TmParallelApply is looking within. If I have something in my work space with the right name, the error does not happen. Examples below

Fails, because I don't have anything in my work space named stopword_vec
```
rm(list=ls())
data(nih_sample)
 dtm <- CreateDtm(nih_sample$ABSTRACT_TEXT, 
                  doc_names = nih_sample$APPLICATION_ID, 
                  ngram_window = c(1, 2))
```

Fails for the same reason
```
rm(list=ls())
data(nih_sample)
 dtm <- CreateDtm(nih_sample$ABSTRACT_TEXT, 
                  stopword_vec = c("blah")
                  doc_names = nih_sample$APPLICATION_ID, 
                  ngram_window = c(1, 2))
```

Does not fail, even though this is not the stopword_vec passed to the function
```
rm(list=ls())
data(nih_sample)
stopword_vec <- "blah"
 dtm <- CreateDtm(nih_sample$ABSTRACT_TEXT, 
                  doc_names = nih_sample$APPLICATION_ID, 
                  ngram_window = c(1, 2))
```

It looks like the source might be `parallel::clusterExport`

**Comment by TommyJones** [comment]
Eek. Ok. Looking into this.

**Comment by TommyJones** [comment]
Think I got it. I added an option to declare a default search environment to TmParallelApply. Testing now. Will close the issue if it passes all tests.

**Comment by TommyJones** [comment]
Tested. Please open a new issue if it crops up again elsewhere.
