### ISSUE TITLE
`...` argument conflicts in `FitLdaModel`

### ISSUE THREAD

**Issue by TommyJones** [TommyJones/textmineR#24]
`Dtm2Docs` does not receive `...` at all (though it calls parallelization)
`...` is allocated to both `lda::lda.collapsed.gibbs.sampler` and `TmParallelApply`

The result is that passing args though `...` will crash either `TmParallelApply` or `lda::lda.collapsed.gibbs.sampler`

**Comment by WilDoane** [comment]
Is there a use of formals() and match.arg() here that would allow you to
inspect the args of lda::lda.collapsed.gibbs.sampler and TmParallelApply
and only pass thru matching args?

**Comment by TommyJones** [comment]
I'm hopefully going to get to this this weekend.

**Comment by TommyJones** [comment]
@WilDoane, that was harder to fix than I imagined. Specifically, there are several articles alluding to a solution, but not many that explicitly state it. 

The solution I figured out was...

```
myfun <- function(a, b, ...){
  dots <-  list(...)

  fun1_arglist <- c(list(a = a), dots[ names(dots) %in% names(formals(fun1)) ] )

  result1 <- do.call(fun1, fun1_arglist)

  fun2_arglist <- c(list(b = b), dots[ names(dots) %in% names(formals(fun2)) ] )

  result2 <- do.call(fun2, fun2_arglist)

  # rest of function below...
}
```

Update itself will be up shortly. I'll also turn this into a release and push to CRAN today if I am confident that I won't break anything else...
