### ISSUE TITLE
Wordclouds of terms from each topic in model (Lda, Ctm, Lsa)

### ISSUE THREAD

**Issue by jdistlr** [TommyJones/textmineR#27]
Hello textmineR-Community

Maybe this is wrong place to ask for such a task ... but I can't get it to work.

The goal is to visualize the `GetTopTerms` (M=5) for individual topics (k=4) from `FitLdaModel`, `FitLsaModel` and `FitCtmModel`. 

Therefore I took the `TopicWordCloud` function  (https://github.com/TommyJones/textmineR/blob/master/extra_functions/TopicWordCloud.R).

The frequencies for the single clouds I extracted from `phi` with:
```freq <- apply(model$phi, 1, function(x){ x[ order(x, decreasing=TRUE) ][ 1:M ] }```
A copy from the GetTopTerms function, without the names.

So ... am I correct in assuming (for Lda and Ctm) that freq is the probabilities of the terms, matching the related topic? My outputs are always below 0,1 on each topic-term-group. Seems that I miss some important facts about knowing what this kind of metric explains. Additionally ... what does the `phi` of the `FitLsaModel` describes exactly?

The second problem I can't solve is hidden in the Lsa context. From time to time (fitting models) there are negative values (in a topic-term-group). The above `TopicWordCloud` can't handle most of the `phi` outputs. My unsuspicious assumption was to make `model$phi` abs() before handle over to the `TopicWordCloud` function. But the results differ from `GetTopTerms` out of the LSA `model` to the resulting wordcloud (see attached example, sorry for the quirky german terms :D). 

Below the output of my unsuccessful trials ... 
[TopicDetection_Report_20111108.htm.zip](https://github.com/TommyJones/textmineR/files/579321/TopicDetection_Report_20111108.htm.zip) (a single HTML file with base64 inlined wordclouds).

So ... what is the right way in plotting wordclouds for each topic while using textmineR's phi of each FitxModel function?

Hope to get help ... although it's not an issue.

**Comment by TommyJones** [comment]
`TopicWordCloud()` is just a wrapper for `wordcloud::wordcloud()`. I think the proper inputs would be more explicit if you used `wordcloud` directly. You basically need a character vector of words, and a numeric vector of weights. The weights are the rows of the `phi` matrices, whether you're using LDA, LSA, or something else. At a minimum, you'll probably have to play with the `min.freq` argument.

`wordcloud(words = colnames(phi) ,freq = phi[ 1, ] * 100 ,scale=c(4,.5),min.freq=3,max.words=20, random.order=FALSE)`

**Comment by TommyJones** [comment]
I'm going to mark this as closed. Please re-open if you're having any other issues.
