### ISSUE TITLE
suppress verbose in textmineR::CreateDtm()

### ISSUE THREAD

**Issue by sunsiyu** [TommyJones/textmineR#28]
Hi, 

When using the function CreateDtm() in textmineR, the progress status verbose cannot be suppressed regardless of  suppressWarnings(), suppressMessages(), invisible(), or try(silent = T) etc.

For strictly non-verbose environment, this is very undesirable. Could this be somehow modified in a way that leave the option of verbose to the user?  

stackoverflow question [here](http://stackoverflow.com/questions/42512918/how-to-suppress-the-verbose-from-createdtm-in-the-textminer-r-package)

**Comment by TommyJones** [comment]
Thanks for bringing this to my attention. I will have to add a verbose argument since the underlying function producing the output is `text2vec::create_dtm`. Shouldn't be an issue. I will add that to the next minor release. It will be up on CRAN sometime in March.

**Comment by TommyJones** [comment]
I've just pushed a development version to GitHub that incorporates this change. If you use devtools (or any other method to build from source) you can grab version 2.0.4.9999. I will close this issue with the release of version 2.0.5.

**Comment by TommyJones** [comment]
Yikes. Upon testing that doesn't do it because the source is in `text2vec::create_vocabulary` which does not have a `verbose` argument. I will have to dig deeper to see what can be done.

**Comment by dselivanov** [comment]
`itoken` has verbose argument

3 мар. 2017 г. 6:51 ДП пользователь "Tommy Jones" <notifications@github.com>
написал:

**Comment by TommyJones** [comment]
It worked! Thank you @dselivanov. I'll close this issue once the next version is released to CRAN

**Comment by TommyJones** [comment]
Closing. Latest version includes this feature.
