### ISSUE TITLE
tm, rweka dependencies

### ISSUE THREAD

**Issue by dselivanov** [TommyJones/textmineR#3]
Hi! I also often use `lda` package, so can be interesting in `textmineR`. `tm` and `RWeka` are very inefficient packages. You can be interested in my [text2vec](https://github.com/dselivanov/text2vec) package, which I just submitted  to CRAN. It **much faster**, don't require `rJava` and can create corpuses in `lda_c` format suggested by `lda` package:
```r
library(text2vec)
library(magrittr)
data("movie_review")
it <- itoken(movie_review$review, preprocess_function = tolower, 
             tokenizer = word_tokenizer)

vocab <- vocabulary(it, ngram = c(1L, 1L)) %>% 
  prune_vocabulary(term_count_min = 5)

it <- itoken(movie_review$review, preprocess_function = tolower, 
             tokenizer = word_tokenizer)

lda_c_dtm <- create_vocab_corpus(it, vocab) %>% 
  get_dtm('lda_c')
```

**Comment by TommyJones** [comment]
Dimitriy,

Thank you. I'm planning to remove textmineR's Java dependencies in version
2.0. I'll check your library out.

Tommy

**Comment by TommyJones** [comment]
Hi Dimitriy,

I'm going to close this issue since, well, it's not really an issue. I've downloaded text2vec and evaluate using it instead of tm for a future release.

Tommy
