### ISSUE TITLE
Correct description on coherence in vignette. 

### ISSUE THREAD

**Issue by TommyJones** [TommyJones/textmineR#38]
At one point, you say:
"For each pair of words {a,b} in the top M words in a topic, probabilistic coherence calculates P(b|a)−P(b), where {a} is more probable than {b} in the topic."

Then in the numbered list below, you have: 
"For example, suppose the top 4 words in a topic are {a,b,c,d}. Then, we calculate
P(a|b)−P(b), P(a|c)−P(c), P(a|d)−P(d)
P(b|c)−P(c), P(b|d)−P(d)
P(c|d)−P(d)"

**Comment by mrandsrand** [comment]
Sorry to bother you, but I really don't understand why the two quotes use different statistics. Could you explain?

> At one point, you say: "For each pair of words {a,b} in the top M words in a topic, probabilistic coherence calculates P(b|a)−P(b), where {a} is more probable than {b} in the topic."
> 
> Then in the numbered list below, you have: "For example, suppose the top 4 words in a topic are {a,b,c,d}. Then, we calculate P(a|b)−P(b), P(a|c)−P(c), P(a|d)−P(d) P(b|c)−P(c), P(b|d)−P(d) P(c|d)−P(d)"
