### ISSUE TITLE
License is not super clear

### ISSUE THREAD

**Issue by pombredanne** [TommyJones/textmineR#74]
Hi!
The license in the DESCRIPTION is described as `MIT + file LICENSE` and the LICENSE file contains this statement 
```
YEAR: 2019
COPYRIGHT HOLDER: Thomas W. Jones
```
which reads more like a terse copyright notice than a license notice or text. 

So there is really no license text at all present in the repo. It could be good to have the license in the LICENSE since the primary condition of the MIT is to have a copy of the license. Otherwise anyone redistributing this package would have to add it themselves.
Also MIT would be enough in the DESCRIPTION .
I hope this makes sense!

**Comment by TommyJones** [comment]
Hi. Thanks for taking an interest in this. And my apologies for a delayed response. 

I agree that the license could be clearer. Unfortunately, this package is built primarily for the CRAN repository. Their policies require me to use their template. Specifically, I am only to use the lines for year and copyright holder in my LICENSE file. 

More information is here: https://cran.r-project.org/web/licenses/MIT

I’d be open for a suggestion about how to bridge the gap between CRAN and textmineR standing on its own on GitHub. But CRAN is the priority.

**Comment by TommyJones** [comment]
Also if I misunderstood, please let me know.

**Comment by pombredanne** [comment]
@TommyJones thanks for taking the time to look into this. This was reported in https://clearlydefined.io/definitions/git/github/tommyjones/textminer/7ced28c7df42b53599c2467a31d682b6ab146755  where we are trying to help projects provide clearer licensing info (this is a project under the https://opensource.org ) 

So it looks like CRAN ways are a tad weird... if you read the MIT text, the only requirement is smack in the middle saying: `The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.` and if I understand what you are saying, including the "permission notice" of the MIT is not allowed in CRAN? Would you know who I could reach out at CRAN?

**Comment by TommyJones** [comment]
I don't have any specific knowledge of who runs this at CRAN. But the contact info for package submission is cran-submissions@r-project.org. (I got this address here: https://cran.r-project.org/submit.html) 

For a fair warning: there are about 6 volunteers who go through ~100+ package submissions daily. So, I'd give even odds on whether you get a response. I hope you do since this is a worthy cause, IMHO.

I'll close this issue for now. But will re-open or re-address later if needed.
