### ISSUE TITLE
CalcTopicModelR2

### ISSUE THREAD

**Issue by simone-mordue** [TommyJones/textmineR#76]
Hello, 

I am getting an error when using the function FitLdaModel using the following code, 

```
dtm<-CreateDtm(doc_vec = txt2$text,
                doc_names = txt2$doc_id, 
                ngram_window = c(1,2),
                stopword_vec = c(stopwords::stopwords("en"),
                                 searchterms),
                lower = TRUE,
                remove_punctuation = TRUE,
                remove_numbers = TRUE
                )

model<-FitLdaModel(dtm=dtm, 
                   k=28, 
                   iterations = 100, 
                   burnin = 10, 
                   alpha = 0.1,
                   beta = 0.05,
                   optimize_alpha = TRUE,
                   calc_likelihood = TRUE,
                   calc_coherence = TRUE,
                   calc_r2 = TRUE,
                   cpus =2)
```
The error message I am getting is; 

`Error in CalcTopicModelR2(dtm, result$phi, result$theta, ...) : 
  document names do not match between dtm and theta. Check rownames of both matrices.`

Please could you have a look at this and let me know if you can identify the problem? I could email you the dtm.rda file if it helps.

Many thanks,
Simone

**Comment by TommyJones** [comment]
Hi, can you try running the same model with `calc_r2 = FALSE`? Want to try to isolate the issue.

**Comment by TommyJones** [comment]
@simone-mordue are you still having this issue? If so, could you please provide a small reproducible example?

**Comment by TommyJones** [comment]
Closing because I haven't heard back. If you need help troubleshooting, feel free to shoot me an email.

**Comment by sethhenrymorgan** [comment]
I got this same error. Everything works when I select `calc_r2 = F`. Strangely, when I try to find the differences in row names I don't find any. `setdiff(rownames(dtm), rownames(model$theta))` returns character(0).

**Comment by TommyJones** [comment]
Can you provide a small reproducible example? textmineR ships with text
data you can use without me having to use yours. see data("nih_sample") or
data("nih_sample_dtm").

**Comment by sethhenrymorgan** [comment]
Turns out this error can be caused by a duplicate in the dataset that the doc_names are drawn from. I don't know if that was simone-mordue's issue above, but that's what tripped me up. Here's an example just in case that's useful at all:

```
library(textmineR)
data("nih_sample")

#create duplicate
df <- rbind(nih_sample, nih_sample[1,])

#make dtm
dtm <- CreateDtm(df$`ABSTRACT_TEXT`, doc_names = df$`PROJECT_TITLE`)

#fit model
model <- FitLdaModel(dtm, k = 8, iterations = 500, burnin = -1, calc_r2=T, calc_likelihood=T, calc_coherence = T)
```
