### ISSUE TITLE
LDAvis

### ISSUE THREAD

**Issue by JavierDeLaHoz** [TommyJones/textmineR#78]
I am using the FitLdaModel function and after obtaining the model I use the LDAvis package to visualize, however, I have observed that although the words of the topics are the same, the number assigned to the topics is not the same.

**Comment by JavierDeLaHoz** [comment]
este es e código que he utilizado model

tm2LDAvis <- function(model){
    if ("lda_topic_model" %in% class(model)){
        if (ncol(model$theta) < 3) stop("The model must contain > 2 topics")
        ldavis <- LDAvis::createJSON(
            phi = model$phi, 
            theta = model$theta,
            vocab = colnames(model$phi),
            doc.length = slam::row_sums(model$data, na.rm = TRUE),
            term.frequency = slam::col_sums(model$data, na.rm = TRUE))
    } else if ("LDA_VEM" %in% class(model)){ #Taken from https://gist.github.com/trinker/477d7ae65ff6ca73cace
        post <- topicmodels::posterior(model)
        if (ncol(post[["topics"]]) < 3) stop("The model must contain > 2 topics")
        mat <- model@wordassignments
        ldavis <- LDAvis::createJSON(
            phi = post[["terms"]], 
            theta = post[["topics"]],
            vocab = colnames(post[["terms"]]),
            doc.length = slam::row_sums(mat, na.rm = TRUE),
            term.frequency = slam::col_sums(mat, na.rm = TRUE))
    } else {
        stop("Class of topic model not recognised. Must be of class LDA_VEM or lda_topic_model")
    }
    return(ldavis)
    R=15
}
LDAvis::serVis(tm2LDAvis(model))

**Comment by TommyJones** [comment]
Hi there. Thanks for using textmineR and, LDAvis is a great way to explore topic models. Unfortunately this isn't an issue with textmineR, so there's nothing I can do. It looks like LDAviz somehow changes the index when it runs. See #72 

You can try to take the issue up with LDAviz or manually go through the model manually and match up the textmineR content with the LDAviz content.
