### ISSUE TITLE
CalcHellingerDist seems to modify in place

### ISSUE THREAD

**Issue by torven-schalk** [TommyJones/textmineR#83]
When running CalcHellingerDist on an lda object it seems to set all betas to 1 afterwards, for example if I want to use the broom::tidy function

> summary(broom::tidy(lda_nyt1985_y_n_ddg, matrix = "beta"))
     topic       term                beta          
 Min.   :1   Length:19895       Min.   :8.028e-06  
 1st Qu.:2   Class :character   1st Qu.:8.168e-06  
 Median :3   Mode  :character   Median :9.171e-06  
 Mean   :3                      Mean   :2.513e-04  
 3rd Qu.:4                      3rd Qu.:1.686e-04  
 Max.   :5                      Max.   :1.855e-02  
> summary(broom::tidy(lda_nyt1985_y_n_ddg, matrix = "beta"))
     topic       term                beta          
 Min.   :1   Length:19895       Min.   :8.028e-06  
 1st Qu.:2   Class :character   1st Qu.:8.168e-06  
 Median :3   Mode  :character   Median :9.171e-06  
 Mean   :3                      Mean   :2.513e-04  
 3rd Qu.:4                      3rd Qu.:1.686e-04  
 Max.   :5                      Max.   :1.855e-02  
> nyt1985_y_n_dist <- textmineR::CalcHellingerDist(lda_nyt1985_y_n_ddg@beta)
> summary(broom::tidy(lda_nyt1985_y_n_ddg, matrix = "beta"))
     topic       term                beta  
 Min.   :1   Length:19895       Min.   :1  
 1st Qu.:2   Class :character   1st Qu.:1  
 Median :3   Mode  :character   Median :1  
 Mean   :3                      Mean   :1  
 3rd Qu.:4                      3rd Qu.:1  
 Max.   :5                      Max.   :1

**Comment by TommyJones** [comment]
Hi. Can you include a small reproducible example? I can take it from there.

**Comment by torven-schalk** [comment]
library(topicmodels)
data("AssociatedPress")

lda_owl <- topicmodels::LDA(AssociatedPress, k = 3, method = "Gibbs",
                            control = list(verbose = 50L, iter = 500, seed = 123))

summary(broom::tidy(lda_owl, matrix = "beta"))
summary(broom::tidy(lda_owl, matrix = "beta"))
dist_owl <- textmineR::CalcHellingerDist(lda_owl@beta)
summary(broom::tidy(lda_owl, matrix = "beta"))

**Comment by TommyJones** [comment]
Strange. This error is reproducible only when calling tidy. 

The below throws an error

```
library(topicmodels)
data("AssociatedPress")

lda_owl <- topicmodels::LDA(AssociatedPress, k = 3, method = "Gibbs",
                            control = list(verbose = 50L, iter = 500, seed = 123))

tidybeta1 <- tidytext::tidy(lda_owl, matrix = "beta")

dist_owl <- textmineR::CalcHellingerDist(lda_owl@beta)

tidybeta2 <- tidytext::tidy(lda_owl, matrix = "beta")

testthat::expect_equal(sum(tidybeta1[[3]] != tidybeta2[[3]]), 0)
```

Set a fresh R session and then the below does not return an error

```
library(topicmodels)
data("AssociatedPress")

lda_owl <- topicmodels::LDA(AssociatedPress, k = 3, method = "Gibbs",
                            control = list(verbose = 50L, iter = 500, seed = 123))

beta1 <- lda_owl@beta

dist_owl <- textmineR::CalcHellingerDist(lda_owl@beta)

beta2 <- lda_owl@beta

testthat::expect_equal(sum(tidybeta1[[3]] != tidybeta2[[3]]), 0)
```

**Comment by TommyJones** [comment]
If run together, it's only when calling tidy that the error occurs. I'm making an edit to the Rcpp code that calculates Hellinger and JSD to force a deep copy. But given the evidence I can't see how this would be a result of `CalcHellingerDist()`.

```
library(topicmodels)
data("AssociatedPress")

lda_owl <- topicmodels::LDA(AssociatedPress, k = 3, method = "Gibbs",
                            control = list(verbose = 50L, iter = 500, seed = 123))

beta1 <- lda_owl@beta

tidybeta1 <- tidytext::tidy(lda_owl, matrix = "beta")

dist_owl <- textmineR::CalcHellingerDist(lda_owl@beta)

beta2 <- lda_owl@beta

tidybeta2 <- tidytext::tidy(lda_owl, matrix = "beta")

testthat::expect_equal(sum(beta1 != beta2), 0) # no error

testthat::expect_equal(sum(tidybeta1[[3]] != tidybeta2[[3]]), 0) # error
```

**Comment by TommyJones** [comment]
Forcing a deep copy makes the issue go away. For the life of me I can't figure out the inconsistency above when using/not using `tidy()`. Computers are hard.

Fixed with https://github.com/TommyJones/textmineR/commit/6449c6f2a17632cf26bf3ab86647781a1f6a310c

Closing now. Have a few more issues to go through before submitting a new version to CRAN
