### ISSUE TITLE
how to obtain word assignment of the original dataset?

### ISSUE THREAD

**Issue by mengliuveronica** [TommyJones/textmineR#90]
Hi Tom,

I want to take the original document-word pairs and find which words in each document were assigned to which topic. I know the "augment" function can do this but it doesn't support textmineR model object. Could you kindly show me how to do this? Many thanks!

Best
Veronica

**Comment by TommyJones** [comment]
Hi Veronica,

If you're looking for something that behaves like this, I'd suggest
checking out tidylda <https://cran.r-project.org/package=tidylda>. It has a
built-in augment function. It doesn't work by The API isn't as stable as
textmineR's, however. Also, it doesn't return which tokens in which
document were assigned to a given topic. Rather, it returns the posterior
probability P(topic|word, document). If you want an explicit topic
assignment, the type argument can be set to "class". Then it just
returns the topic for which P(topic|word, document) is maximized, rather
than the probability for each topic.

Tommy

**Comment by TommyJones** [comment]
Closing this issue. But feel free to ask any more questions you have on the issue here and I'll see if I can help.
